---
title: "Eat Gen Menu"
date: "Updated `r format(Sys.Date(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# load library
library(showtext)
library(fontawesome)

# path to fonts folder
font_paths("fonts")

# add 2 fonts
font_add("arkipelago",
         regular = "Arkipelago.ttf")
font_add("cuprum",
         regular = "Cuprum-Regular.ttf",
         bold = "Cuprum-Bold.ttf",
         italic = "Cuprum-Italic.ttf",
         bolditalic = "Cuprum-BoldItalic.ttf")
```

[`r fontawesome::fa('instagram', fill = '#2C2828')`](https://www.instagram.com/eatgen/){.sm}
[`r fontawesome::fa('whatsapp', fill = '#2C2828')`](https://wa.me/628123800436){.sm}
<a href="https://gofood.link/u/k54ve" class="btn btn-success">Order in GoFood Now</a>

## Promo

- Mie Ayam + Es Teh

## Basic Menu

- Nasi Goreng Biasa
- Nasi Goreng Special
- Nasi Goreng Pete
- Nasi Pecel
- Nasi Pecel Special
- Nasi + Rawon
- Tahu Petis

## Sayuran

- Cah Kangkung
- Cah Tauge

## Ikan

- Nila Menyat-nyat `r fa("pepper-hot", fill = "#FF0000")`
  - `+` sayur
- Nila Goreng
  - `+` lalapan 
  - `+` sambal
- Steak Tenggiri
  - `+` sambal matah
  - `+` sambal kecap
- Sup Tenggiri
- Pepes Nila `r fa("pepper-hot", fill = "#FF0000")`
- Pepes Baby Tuna `r fa("pepper-hot", fill = "#FF0000")`
  - `+` sayur

## Ayam

- Betutu Ayam Kampung `r fa("pepper-hot", fill = "#FF0000")`
- Ayam Telor Asin
- Ayam Teriyaki
  - `+` sayur
- Ayam Goreng Mentega

## Udang

- Udang Telor Asin
- Udang Goreng Tepung
- Udang Mentega
- Udang Panggang
  - `+` sambal matah
  - `+` plecing kangkung

## Minuman

- Teh Tawar
- Teh Manis
- Jeruk 
- Jeruk Special

## Coffee

- Long Black
- Cappucino / Latte
- Flat White
- Mocha

<br>

<a href="https://gofood.link/u/k54ve" class="btn btn-success">Order in GoFood Now</a>